services:
  pg:
    image: postgres:18-alpine
    environment:
      - POSTGRES_PASSWORD=1
  backend:
    container_name: backend
    depends_on:
      - pg
    build: .
    ports:
      - 8888:8888
    environment:
      - PORT=8888
      - PGHOST=pg
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=1
      - PGDATABASE=postgres
  